# The events block is required by nginx.
# It controls how nginx handles connections at the system level.
# We leave it empty to use the default values
# (512 connections per worker, 1 worker process).
events {}

http {
    # Define a group of servers called "backends".
    # nginx will automatically distribute requests between them.
    # By default it uses round-robin: 1st request goes to web1, 2nd to web2, 3rd to web1, etc.
    upstream backends {
        server web1:8000; # first backend server on port 8000
        server web2:8000; # second backend server on port 8000
    }

    server {
        listen 80; # nginx listens for requests on port 80

        # Applies to any incoming request (e.g. /ping, /hello, /anything)
        location / {
            # forwards the request to one of the servers in the "backends" group
            proxy_pass http://backends;

            # passes information about the original client to the backend
            proxy_set_header Host $host;                                 # domain used by the client
            proxy_set_header X-Real-IP $remote_addr;                     # real IP of the client
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # list of IPs along the way
        }
    }
}