# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05proxy\"\x9b\x01\n\x0bHttpRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x30\n\x07headers\x18\x04 \x03(\x0b\x32\x1f.proxy.HttpRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8f\x01\n\x0cHttpResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\x31\n\x07headers\x18\x03 \x03(\x0b\x32 .proxy.HttpResponse.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x46\n\nWebService\x12\x38\n\rHandleRequest\x12\x12.proxy.HttpRequest\x1a\x13.proxy.HttpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HTTPREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_HTTPREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_HTTPRESPONSE_HEADERSENTRY']._loaded_options = None
  _globals['_HTTPRESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_HTTPREQUEST']._serialized_start=25
  _globals['_HTTPREQUEST']._serialized_end=180
  _globals['_HTTPREQUEST_HEADERSENTRY']._serialized_start=134
  _globals['_HTTPREQUEST_HEADERSENTRY']._serialized_end=180
  _globals['_HTTPRESPONSE']._serialized_start=183
  _globals['_HTTPRESPONSE']._serialized_end=326
  _globals['_HTTPRESPONSE_HEADERSENTRY']._serialized_start=134
  _globals['_HTTPRESPONSE_HEADERSENTRY']._serialized_end=180
  _globals['_WEBSERVICE']._serialized_start=328
  _globals['_WEBSERVICE']._serialized_end=398
# @@protoc_insertion_point(module_scope)
